AllCops:
  TargetRubyVersion: 2.7
  SuggestExtensions: false
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/ParameterLists:
  Max: 10

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 120
